"""initial_core_tables

Revision ID: e105134b9dd5
Revises: 
Create Date: 2025-06-27 17:09:44.005724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e105134b9dd5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('supplier_number', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_supplier_number'), 'suppliers', ['supplier_number'], unique=True)
    op.create_table('articles',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('article_number', sa.String(), nullable=True),
    sa.Column('supplier_number', sa.String(), nullable=True),
    sa.Column('article_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('cost_type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('dimension', sa.String(), nullable=True),
    sa.Column('item_no_ext', sa.String(), nullable=True),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('certification', sa.String(length=10), nullable=False),
    sa.Column('sale_unit', sa.String(), nullable=True),
    sa.Column('units_per_sale_unit', sa.Float(), nullable=True),
    sa.Column('unit_per_package', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_number'], ['suppliers.supplier_number'], ),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_index(op.f('ix_articles_article_number'), 'articles', ['article_number'], unique=False)
    op.create_table('article_prices',
    sa.Column('price_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('sale_unit', sa.String(), nullable=True),
    sa.Column('units_per_sale_unit', sa.Float(), nullable=True),
    sa.Column('sale_unit_price_eur', sa.Float(), nullable=True),
    sa.Column('unit_price_eur', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('delivery', sa.Date(), nullable=True),
    sa.Column('costplace', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], ),
    sa.PrimaryKeyConstraint('price_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_prices')
    op.drop_index(op.f('ix_articles_article_number'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_suppliers_supplier_number'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
